services:
  jenkins-server:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-server
    ports:
      - "8083:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  jenkins-agent:
    image: custom-jenkins-agent
    container_name: jenkins-agent
    environment:
      - JENKINS_URL=http://jenkins-server:8080
      - JENKINS_SECRET=b354fb0e1151059cf69a4534871c5dbc16aea5473c40757da0c77275be944671
      - JENKINS_AGENT_NAME=jenkins-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  jenkins_home:
